# Generated by Django 5.1.7 on 2025-09-01 10:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_remove_event_event_type_alter_event_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invitation",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 9, 1, 10, 20, 17, 639798, tzinfo=datetime.timezone.utc
                )
            ),
            preserve_default=False,
        ),
    ]
