# Generated by Django 5.1.7 on 2025-09-15 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_invitation_expires_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="type",
            field=models.CharField(default="wedding", max_length=200),
            preserve_default=False,
        ),
    ]
