# Generated by Django 5.1.7 on 2025-09-16 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0005_event_updated_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="status",
            field=models.CharField(
                choices=[
                    ("ongoing", "Ongoing"),
                    ("completed", "Completed"),
                    ("archived", "Archived"),
                ],
                default="ongoing",
                max_length=20,
            ),
        ),
    ]
