# Generated by Django 5.1.7 on 2025-09-30 20:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0006_event_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="date",
            new_name="end_date",
        ),
        migrations.AddField(
            model_name="event",
            name="start_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
