# Generated by Django 5.1.7 on 2025-10-01 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0007_rename_date_event_end_date_event_start_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="banner_image",
            field=models.ImageField(blank=True, null=True, upload_to="events"),
        ),
    ]
