#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

python3 manage.py migrate --no-input
python3 manage.py collectstatic --no-input
python3 manage.py create_missing_budgets
daphne -b 0.0.0.0 -p 8000 eventnest.asgi:application
