services:
  - type: web
    name: eventnest-api
    runtime: python
    buildCommand: |
      pip install -r requirements/production.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn eventnest.wsgi:application
    autoDeploy: true
    envVars:
      # Non-sensitive variables - can be in YAML
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DJANGO_SETTINGS_MODULE
