# kubernetes/celery-worker.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-worker
  labels:
    app: celery-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: celery-worker
  template:
    metadata:
      labels:
        app: celery-worker
    spec:
      containers:
        - name: celery-worker
          image: gcr.io/big-axiom-469111-n3/eventnest-api:master
          command: ["celery"]
          imagePullPolicy: Always
          args:
            ["-A", "eventnest", "worker", "--loglevel=info", "--concurrency=4"]
          envFrom:
            - configMapRef:
                name: eventnest-config
            - secretRef:
                name: eventnest-secret
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - "celery -A eventnest inspect ping -d celery@$HOSTNAME --timeout=10"
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 15
            failureThreshold: 3
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - "celery -A eventnest inspect active -d celery@$HOSTNAME --timeout=15"
            initialDelaySeconds: 30
            periodSeconds: 15
            timeoutSeconds: 20
            failureThreshold: 3

---
# kubernetes/api-server.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: gcr.io/big-axiom-469111-n3/eventnest-api:master
          imagePullPolicy: Always
          command: ["/start"]
          envFrom:
            - configMapRef:
                name: eventnest-config
            - secretRef:
                name: eventnest-secret
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          volumeMounts:
            - name: api-storage
              mountPath: /app/staticfiles
            - name: api-storage
              mountPath: /app/mediafiles
            - name: gcp-credentials
              mountPath: /secrets
              readOnly: true
          ports:
            - containerPort: 8000
      volumes:
        - name: api-storage
          persistentVolumeClaim:
            claimName: api-pvc
        - name: gcp-credentials
          secret:
            secretName: gcp-creds
            items:
              - key: gcp-credentials.json
                path: gcp-credentials.json

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: gcr.io/big-axiom-469111-n3/webserver:master
          imagePullPolicy: Always
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          volumeMounts:
            - name: api-storage
              mountPath: /app/staticfiles
            - name: api-storage
              mountPath: /app/mediafiles
          ports:
            - containerPort: 80
      volumes:
        - name: api-storage
          persistentVolumeClaim:
            claimName: api-pvc

---
# kubernetes/celery-beat.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-beat
  labels:
    app: celery-beat
spec:
  replicas: 1 # IMPORTANT: Only 1 replica for beat scheduler
  selector:
    matchLabels:
      app: celery-beat
  template:
    metadata:
      labels:
        app: celery-beat
    spec:
      containers:
        - name: celery-beat
          image: gcr.io/big-axiom-469111-n3/eventnest-api:master
          imagePullPolicy: Always
          command: ["/start-celerybeat"]
          envFrom:
            - configMapRef:
                name: eventnest-config
            - secretRef:
                name: eventnest-secret
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          volumeMounts:
            - name: celerybeat-storage
              mountPath: /app/celerybeat
      volumes:
        - name: celerybeat-storage
          persistentVolumeClaim:
            claimName: api-pvc

---
# kubernetes/flower.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flower
  labels:
    app: flower
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flower
  template:
    metadata:
      labels:
        app: flower
    spec:
      containers:
        - name: flower
          image: gcr.io/big-axiom-469111-n3/eventnest-api:master
          imagePullPolicy: Always
          command: ["/start-flower"]
          envFrom:
            - configMapRef:
                name: eventnest-config
            - secretRef:
                name: eventnest-secret
          ports:
            - containerPort: 5555
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"

---
# kubernetes/nginx-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer

---
# kubernetes/api-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
---
# kubernetes/api-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: flower-service
spec:
  selector:
    app: flower
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5555

---
# kubernetes/hpa.yaml - Horizontal Pod Autoscaler
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: celery-worker-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: celery-worker
  minReplicas: 1
  maxReplicas: 1
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 99
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 99